# .github/actions/marketing-copy/action.yml
name: "Marketing Copy"
description: "Draft homepage & email copy from Brand & Content specs"

runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Marketing: generate copy
      run: |
        echo "📝 Generating homepage and email drafts..."
