# .github/actions/forge-scaffold/action.yml
name: "Forge Scaffold"
description: "Scaffold code stubs from UI and Implementation specs"

runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Forge: scaffold stubs
      run: |
        echo "⚙️ Scaffolding UI and API stubs from specs..."
